[program:atd]
command=/usr/sbin/atd -f
user=root
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/var/log/wall-e/atd.out.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/wall-e/atd.err.log
stderr_logfile_maxbytes=0
