[program:cron]
command=/usr/local/bin/run-cron
user=root
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/var/log/wall-e/cron.out.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/wall-e/cron.err.log
stderr_logfile_maxbytes=0
