set -g mouse on
set -g extended-keys on
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB,tmux-256color:RGB"
set -ga terminal-overrides ",xterm-256color:Tc,tmux-256color:Tc"
set -g focus-events on
